/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Resume as PrismaResume,
  ParsedData as PrismaParsedData,
} from "@prisma/client";
import { LocalStorageService } from "src/storage/providers/local/local.storage.service";
import { InputJsonValue } from "src/types";
import { FileDownload, FileUpload } from "src/storage/base/storage.types";
import { LocalStorageFile } from "src/storage/providers/local/local.storage.types";

export class ResumeServiceBase {
  constructor(
    protected readonly prisma: PrismaService,
    protected readonly localStorageService: LocalStorageService
  ) {}

  async count(args: Omit<Prisma.ResumeCountArgs, "select">): Promise<number> {
    return this.prisma.resume.count(args);
  }

  async resumes(args: Prisma.ResumeFindManyArgs): Promise<PrismaResume[]> {
    return this.prisma.resume.findMany(args);
  }
  async resume(
    args: Prisma.ResumeFindUniqueArgs
  ): Promise<PrismaResume | null> {
    return this.prisma.resume.findUnique(args);
  }
  async createResume(args: Prisma.ResumeCreateArgs): Promise<PrismaResume> {
    return this.prisma.resume.create(args);
  }
  async updateResume(args: Prisma.ResumeUpdateArgs): Promise<PrismaResume> {
    return this.prisma.resume.update(args);
  }
  async deleteResume(args: Prisma.ResumeDeleteArgs): Promise<PrismaResume> {
    return this.prisma.resume.delete(args);
  }

  async uploadFile<T extends Prisma.ResumeFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ResumeFindUniqueArgs>,
    file: FileUpload
  ): Promise<PrismaResume> {
    file.filename = `profilePicture-${args.where.id}.${file.filename
      .split(".")
      .pop()}`;
    const containerPath = "file";
    const file = await this.localStorageService.uploadFile(
      file,
      [],
      1000000,
      containerPath
    );

    return await this.prisma.resume.update({
      where: args.where,

      data: {
        file: file as InputJsonValue,
      },
    });
  }

  async downloadFile<T extends Prisma.ResumeFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ResumeFindUniqueArgs>
  ): Promise<FileDownload> {
    const { file } = await this.prisma.resume.findUniqueOrThrow({
      where: args.where,
    });

    return await this.localStorageService.downloadFile(
      file as unknown as LocalStorageFile
    );
  }

  async deleteFile<T extends Prisma.ResumeFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ResumeFindUniqueArgs>
  ): Promise<PrismaResume> {
    const { file } = await this.prisma.resume.findUniqueOrThrow({
      where: args.where,
    });

    await this.localStorageService.deleteFile(
      file as unknown as LocalStorageFile
    );

    return await this.prisma.resume.update({
      where: args.where,

      data: {
        file: Prisma.DbNull,
      },
    });
  }

  async findParsedDataItems(
    parentId: string,
    args: Prisma.ParsedDataFindManyArgs
  ): Promise<PrismaParsedData[]> {
    return this.prisma.resume
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .parsedDataItems(args);
  }
}
