/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ParsedDataService } from "../parsedData.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ParsedDataCreateInput } from "./ParsedDataCreateInput";
import { ParsedData } from "./ParsedData";
import { ParsedDataFindManyArgs } from "./ParsedDataFindManyArgs";
import { ParsedDataWhereUniqueInput } from "./ParsedDataWhereUniqueInput";
import { ParsedDataUpdateInput } from "./ParsedDataUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ParsedDataControllerBase {
  constructor(
    protected readonly service: ParsedDataService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ParsedData })
  @nestAccessControl.UseRoles({
    resource: "ParsedData",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createParsedData(
    @common.Body() data: ParsedDataCreateInput
  ): Promise<ParsedData> {
    return await this.service.createParsedData({
      data: {
        ...data,

        resume: data.resume
          ? {
              connect: data.resume,
            }
          : undefined,
      },
      select: {
        address: true,
        createdAt: true,
        education: true,
        email: true,
        id: true,
        lastName: true,
        name: true,
        phoneNumber: true,

        resume: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        workExperience: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ParsedData] })
  @ApiNestedQuery(ParsedDataFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ParsedData",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async parsedDataItems(@common.Req() request: Request): Promise<ParsedData[]> {
    const args = plainToClass(ParsedDataFindManyArgs, request.query);
    return this.service.parsedDataItems({
      ...args,
      select: {
        address: true,
        createdAt: true,
        education: true,
        email: true,
        id: true,
        lastName: true,
        name: true,
        phoneNumber: true,

        resume: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        workExperience: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ParsedData })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ParsedData",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async parsedData(
    @common.Param() params: ParsedDataWhereUniqueInput
  ): Promise<ParsedData | null> {
    const result = await this.service.parsedData({
      where: params,
      select: {
        address: true,
        createdAt: true,
        education: true,
        email: true,
        id: true,
        lastName: true,
        name: true,
        phoneNumber: true,

        resume: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        workExperience: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ParsedData })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ParsedData",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateParsedData(
    @common.Param() params: ParsedDataWhereUniqueInput,
    @common.Body() data: ParsedDataUpdateInput
  ): Promise<ParsedData | null> {
    try {
      return await this.service.updateParsedData({
        where: params,
        data: {
          ...data,

          resume: data.resume
            ? {
                connect: data.resume,
              }
            : undefined,
        },
        select: {
          address: true,
          createdAt: true,
          education: true,
          email: true,
          id: true,
          lastName: true,
          name: true,
          phoneNumber: true,

          resume: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          workExperience: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ParsedData })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ParsedData",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteParsedData(
    @common.Param() params: ParsedDataWhereUniqueInput
  ): Promise<ParsedData | null> {
    try {
      return await this.service.deleteParsedData({
        where: params,
        select: {
          address: true,
          createdAt: true,
          education: true,
          email: true,
          id: true,
          lastName: true,
          name: true,
          phoneNumber: true,

          resume: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          workExperience: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
